spring.mvc.dispatch-options-request: true
spring:
  mvc:
    dispatch-options-request=true:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/sahelance4.0
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        format_sql: true
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:/database/db.changelog.xml
    enabled: true
server:
  port: 8080
spring.datasource.testOnBorrow: true
spring.datasource.timeBetweenEvictionRunsMillis: 60000
spring.datasource.validationQuery: SELECT 1

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413sss28472B4B6250645367566B5970
      expiration: 600000000
      refresh-token:
        expiration: 904800000 # 7 days